### ISSUE TITLE
assertLooksLike gives false positives

### ISSUE THREAD

**Issue by stevenmathews** [jvanbruegge/snabbdom-looks-like#1]
[Minimal repro](https://github.com/stevenmathews/snabbdom-looks-like-repro)

I would expect each of the 3 tests to fail, but only the third one does.

**Comment by jvanbruegge** [comment]
The first one does not fail because if the "expected" value (second argument) does not have a property, but the "actual" value is allowed to have additional properties.
The second one should fail though

**Comment by jvanbruegge** [comment]
I published a fix for the second test case as `1.0.5`, I also added your example as regression test

**Comment by stevenmathews** [comment]
cheers @jvanbruegge :-)
